---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# APRENDIZADO DE MÁQUINA ESTATÍSTICO PARA ESTIMATIVA DA EMISSÃO DE CO~2~ DO SOLO EM ÁREAS AGRÍCOLAS

**Beneficiário**: Luis Felipe Trevelim

**Responsável**: Alan Rodrigo Panosso

**Resumo**: A concentração de gases de efeito estufa (GEE) na atmosfera, como o dióxido de carbono (CO~2~), aumentou consideravelmente devido a fontes antropogênicas. No Brasil, atividades agrícolas e florestais contribuem substancialmente para as emissões de CO~2~, principalmente devido ao desmatamento e à conversão de florestas nativas. Estudos anteriores demonstraram que FCO2 pode ser modelada com alta precisão usando uma grande quantidade de variáveis ambientais. No entanto, a conversão a longo prazo de florestas nativas para agroecossistemas ainda é pouco compreendida, especialmente no contexto brasileiro. Assim, a hipótese central é que as mudanças no uso da terra para fins agrícolas alteram os atributos químicos e físicos do solo, induzindo mudanças na emissão de CO2. Este projeto visa investigar a emissão de CO~2~ do solo (FCO2) em áreas agrícolas do bioma Cerrado, utilizando técnicas de aprendizado de máquina estatístico para modelar FCO2 com base em demais variáveis associadas.

**Palavras-chaves**: respiração do solo, inteligência artificial, mudanças climáticas, aprendizado de máquina.

### [1-Faxina](https://arpanosso.github.io/projeto-trevelimlf/Docs/faxina.html)

### 2 - Importação e Tratamento 

### 3 - Análise Exploratória

### 4 - Modelagem T1
